inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 30

RSpec/LeakyConstantDeclaration:
  Enabled: false
