inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable

# ************************
# LAYOUT
# ************************

Layout/LineLength:
  Max: 130

# ************************
# METRICS
# ************************

# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Enabled: false

# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 30

# ************************
# RSPEC
# ************************
RSpec/LeakyConstantDeclaration:
  Enabled: false
